version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: blogdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./blog-platform-backend
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000   # 👈 dev mode
    volumes:
      - ./blog-platform-backend:/app
      - media_data:/app/media
      - static_data:/app/staticfiles
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/blogdb
      - DJANGO_SETTINGS_MODULE=blog_platform_backend.settings
      - SECRET_KEY=supersecretkey
      - DEBUG=1
      - ALLOWED_HOSTS=*

  frontend:
    build:
      context: ./blog-platform-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    stdin_open: true
    tty: true

volumes:
  postgres_data:
  media_data:
  static_data:

env_file:
  - .env